version: 2.1
jobs:
  build:
    machine: true
    resource_class: logan/machine-runner
    steps:
      - run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
      - run: nvm 
workflows:
  build-workflow:
    jobs:
      - build
