version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
      
jobs:
  runner-test:
    machine: true
    resource_class: logan/machine-runner
    steps:
      - checkout
      - run: docker build . -t testing

      
