version: 2.1
jobs:
  build:
    machine: true
    resource_class: logan/machine-runner
    steps:
      - run: echo "This is being run multiple times!"
workflows:
  build-workflow:
    jobs:
      - build
