version: 2.1
jobs:
  build:
    machine: true
    parallelism: 4
    resource_class: logan/windows-runner-aws-2019
    steps:
      - run: echo "This is being run multiple times!"
workflows:
  build-workflow:
    jobs:
      - build
