version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
      
jobs:
  runner-test:
    machine: true
    resource_class: logan/machine-runner
    steps:
      - checkout
      - run: sudo docker build . -t testing
      - run: sudo docker run --privileged -d testing
      - run: sudo docker ps -a
      - run: sudo docker inspect --format='{{.HostConfig.Privileged}}' 4a83b454462a
      
