version: 2.1
jobs:
  build:
    machine: true
    resource_class: logan/machine-runner
    steps:
      - run: echo $HOME
      #- run: |
      #    export NVM_DIR="/home/ubuntu/.nvm"
      #    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
      #    nvm
      - run: |
          source ~/.bashrc
          nvm
workflows:
  build-workflow:
    jobs:
      - build
