version: 2.1
jobs:
  build:
    machine: true
    resource_class: logan/machine-runner
    steps:
      - run: |
          sudo apt-get update && \
            sudo apt-get install -y dotnet-sdk-8.0
      - run: |
            echo "Installing trx2junit"
            dotnet tool install -g trx2junit &&
            echo 'export PATH="$PATH:/root/.dotnet/tools"' >> $BASH_ENV
      - run: dotnet tool list --global
      - run: echo $BASH_ENV
      - run: trx2junit --help
workflows:
  build-workflow:
    jobs:
      - build
