version: 2.1

setup: true
orbs:
  continuation: circleci/continuation@1.0.0

# our defined job, and its steps
jobs:
  set_up:
    machine: true
    resource_class: logan/windows-runner
    steps:
      - checkout # checkout code
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml # use newly generated config to continue
      - run: echo "random commit bc i forgot jq" 

workflows:
  setup:
    jobs:
      - set_up
