version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
      - runner-test-1
      - runner-test-2
jobs:
  runner-test:
    machine: true
    resource_class: logan/windows-runner
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: sleep 10
  runner-test-1:
    machine: true
    resource_class: logan/windows-runner
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: sleep 20
  runner-test-2:
    machine: true
    resource_class: logan/windows-runner
    steps:
      - run: echo "Hi I'm on Runners!"
      
