version: 2.1
jobs:
  build:
    machine: true
    resource_class: logan/aws-machine-runner-test
    steps:
      - run: echo "Hi I'm on a Container Rr!"
workflows:
  build-workflow:
    jobs:
      - build
