version: 2.1
jobs:
  build:
    machine: true
    resource_class: logan/machine-runner
    steps:
      - run: whoami
      - run: sudo mkdir test-results
workflows:
  build-workflow:
    jobs:
      - build
