version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build-and-push:
    machine: true
    resource_class: logan/docker
    steps:
      - run: echo "hello"
      
workflows:
  build_and_push_image:
    jobs:
      - build-and-push


      
      
