version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1


workflows:
  testing:
    jobs:
      - runner-test
      
jobs:
  runner-test:
    machine: true
    resource_class: logan/windows-runner
    shell: powershell.exe
    steps:
      - run:
          name: List files
          command: ls D:\asd
      - persist_to_workspace:
          root: D:\
          paths:
            - asd\*
      
