version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1


workflows:
  testing:
    jobs:
      - runner-test
      
jobs:
  runner-test:
    machine: true
    resource_class: logan/windows-runner
    shell: powershell.exe
    steps:
      - checkout
      - run: 
          name: install choco
          command: |
            Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      - run: choco

      
